### ISSUE TITLE
No incoming names or accuracy metrics

### ISSUE THREAD

**Issue by ldemaz** [agroimpacts/learner#1]
Looks like there is a failure to select incoming names or report accuracy metrics. 

See issues [#26](https://github.com/agroimpacts/issues/issues/26)

Accuracy metrics:
<img width="753" alt="Screenshot 2019-09-07 08 34 12" src="https://user-images.githubusercontent.com/3401881/64475000-87f0c880-d14a-11e9-9e0a-e13b67b5d9fa.png">

**Comment by LLeiSong** [comment]
This is not a bug. I keep the old style of AOI id, I think it is more readable and less confusing.

The failure happened before is because of the run_DB_insert.py. Two things were done to fix this:
1. Modify the bootstrap.sh in` labeler/terraform`. 
2. Add all access inbound rules in security group used by labeller to the security group used in EMR instances to allow it to touch the DB.
