### ISSUE TITLE
Incomplete probability maps

### ISSUE THREAD

**Issue by ldemaz** [agroimpacts/learner#2]
The probability map outputs are only producing values for a single cell in each tile:

![Screenshot 2019-10-02 15 21 02](https://user-images.githubusercontent.com/3401881/66074919-5a6c2480-e528-11e9-94af-68a9b68bf524.png)
![Screenshot 2019-10-02 15 21 27](https://user-images.githubusercontent.com/3401881/66074920-5b9d5180-e528-11e9-9baa-68f2d9399538.png)

  
I suspect the problem is somewhere starting [here](https://github.com/agroimpacts/learner/blob/bf3759f15a4f0fec946c2e23816263e0c114b6de/run_it/run_geopyspark.py#L749), but will likely also be [here](https://github.com/agroimpacts/learner/blob/bf3759f15a4f0fec946c2e23816263e0c114b6de/run_it/run_geopyspark.py#L725)

**Comment by LLeiSong** [comment]
If I remember correctly, the probabilities saved out for comparison should only have one gird within a tile.

**Comment by ldemaz** [comment]
Is that right? Probably a waste to create any sampling images then.

**Comment by LLeiSong** [comment]
I think so. If you check the old ones, they are the same style. We just saved out but didn't use them seriously before. But saving out these images doesn't take long. It just an incidental thing.

**Comment by BkLuo** [comment]
It is because only the sampled cells are put into prediction, not tiles containing the sampled cells, see <a href = "https://github.com/agroimpacts/learner/blob/bf3759f15a4f0fec946c2e23816263e0c114b6de/run_it/run_geopyspark.py#L741-L749">this lines</a>. 
Replacing `filtered_names_sample` with <a href = "https://github.com/agroimpacts/learner/blob/5821cfdc8456117ffa0d288fbb4f1160bee0d8c1/run_it/run_geopyspark.py#L742-L749">this</a> can solve the problem. This new `filtered_names_sample` is all the cells sharing tiles with the sampled cells. 

Here is the tested result on sampling 2 probability maps from a dataset with 6 tiles:
![image](https://user-images.githubusercontent.com/42148420/66181647-8deda280-e63f-11e9-93c3-221f1f27aa45.png)
